skills = {
    'python': ['python', 'PYTHON'],
    'ml': ['machine learning', 'ml', 'ML'],
    'ai': ['artificial intelligence', 'ai', 'AI'],
    'ds': ['data science', 'ds', 'DS'],
    'sql': ['sql', 'SQL', 'mysql', 'MYSQL'],
    'r': ['r', 'R'],
    'dsa': ['data structure and algorithm', 'data structure', 'dsa'],
    'php': ['PHP', 'php'],
    'java': ['JAVA', 'java'],
    'javascript': ['JAVASCRIPT', 'javascript', 'nodejs'],
    'html': ['HTML', 'html', 'Hyper text markup language'],
    'css': ['CSS', 'css', 'cascaded style sheet'],
    'hadoop': ['HADOOP', 'hadoop', 'bigdata', 'BIGDATA', 'hdfs', 'HDFS', 'mapreduce', 'MAPREDUCE', 'hive', 'HIVE', 'pig', 'PIG', 'mahoot', 'MAHOOT', 'hbase', 'HBASE'],
    'problem_solving': ['problem solving'],
    'data_acquisition': ['daav', 'DAAV', 'data acquisition'],
    'critical_thinking': ['critical thinking'],
    'teamwork': ['teamwork'],
    'leadership': ['leadership'],
    'reasoning_skills': ['reasoning skills'],
    'software_development': ['software development'],
    'computer_networks': ['cn', 'CN', 'computer networks'],
    'devops': ['devops', 'DevOps'],
    'docker': ['Docker', 'docker'],
    'kubernetes': ['Kubernetes', 'kubernetes'],
    'cloud_computing': ['cloud computing', 'cloud', 'Cloud Computing'],
    'agile': ['agile methodology', 'agile'],
    'scrum': ['scrum', 'Scrum'],
    'git': ['Git', 'git', 'version control'],
    'aws': ['AWS', 'Amazon Web Services'],
    'azure': ['Azure', 'Microsoft Azure'],
    'mongodb': ['MongoDB', 'mongodb', 'NoSQL'],
    'postgresql': ['PostgreSQL', 'postgresql'],
    'tensorflow': ['TensorFlow', 'tensorflow'],
    'keras': ['Keras', 'keras'],
    'pytorch': ['PyTorch', 'pytorch'],
    'nlp': ['natural language processing', 'NLP'],
    'opencv': ['OpenCV', 'opencv'],
    'react': ['React', 'react'],
    'vue': ['Vue.js', 'vue'],
    'angular': ['Angular', 'angular'],
    'django': ['Django', 'django'],
    'flask': ['Flask', 'flask'],
    'spring': ['Spring', 'spring framework'],
    'android': ['Android', 'android'],
    'ios': ['iOS', 'ios'],
    'mobile_app': ['mobile app development', 'mobile development'],
    'web_development': ['web development', 'front-end', 'back-end'],
    'full_stack': ['full-stack development', 'full stack'],
    'ui_ux': ['UI/UX design', 'user interface', 'user experience'],
    'agile': ['agile methodology', 'agile'],
    'scrum': ['scrum', 'Scrum'],
    'cybersecurity': ['cybersecurity', 'security'],
    'blockchain': ['blockchain'],
    'iot': ['IoT', 'internet of things'],
    'edge_computing': ['edge computing'],
    'data_analytics': ['data analytics'],
    'data_visualization': ['data visualization'],
    'business_intelligence': ['business intelligence', 'BI'],
    'predictive_analytics': ['predictive analytics'],
    'deep_learning': ['deep learning'],
    'neural_networks': ['neural networks'],
    'computer_vision': ['computer vision'],
    'natural_language_processing': ['natural language processing', 'NLP'],
    'reinforcement_learning': ['reinforcement learning'],
    'data_engineering': ['data engineering'],
    'big_data': ['big data', 'Big Data'],
    'etl': ['ETL', 'extract-transform-load'],
    'sql': ['SQL', 'Structured Query Language'],
    'nosql': ['NoSQL', 'NoSQL databases'],
    'data_warehousing': ['data warehousing'],
    'data_mining': ['data mining'],
    'business_analysis': ['business analysis'],
    'product_management': ['product management'],
    'project_management': ['project management'],
    'time_management': ['time management'],
    'communication_skills': ['communication skills'],
    'presentation_skills': ['presentation skills'],
    'negotiation_skills': ['negotiation skills'],
    'problem-solving_skills': ['problem-solving skills'],
    'critical_thinking': ['critical thinking'],
    'analytical_skills': ['analytical skills'],
    'creativity': ['creativity'],
    'innovation': ['innovation'],
    'emotional_intelligence': ['emotional intelligence'],
    'leadership': ['leadership'],
    'adaptability': ['adaptability'],
    'resilience': ['resilience'],
    'teamwork': ['teamwork'],
    'interpersonal_skills': ['interpersonal skills'],
    'multitasking': ['multitasking'],
    'customer_service': ['customer service'],
    'sales': ['sales'],
    'marketing': ['marketing'],
    'finance': ['finance'],
    'human_resources': ['human resources', 'HR'],
    'supply_chain_management': ['supply chain management'],
    'logistics': ['logistics'],
    'quality_control': ['quality control'],
    'manufacturing': ['manufacturing'],
    'procurement': ['procurement'],
    'inventory_management': ['inventory management'],
    'retail': ['retail'],
    'e-commerce': ['e-commerce'],
    'healthcare': ['healthcare'],
    'telemedicine': ['telemedicine'],
    'pharmaceuticals': ['pharmaceuticals'],
    'medical_devices': ['medical devices'],
    'bioinformatics': ['bioinformatics'],
    'energy': ['energy'],
    'sustainability': ['sustainability'],
    'environmental_science': ['environmental science'],
    'climate_change': ['climate change'],
    'renewable_energy': ['renewable energy'],
    'solar_energy': ['solar energy'],
    'wind_energy': ['wind energy'],
    'nuclear_energy': ['nuclear energy'],
    'oil_and_gas': ['oil and gas'],
    'petroleum_engineering': ['petroleum engineering'],
    'chemical_engineering': ['chemical engineering'],
    'civil_engineering': ['civil engineering'],
    'electrical_engineering': ['electrical engineering'],
    'mechanical_engineering': ['mechanical engineering'],
    'aerospace_engineering': ['aerospace engineering'],
    'biomedical_engineering': ['biomedical engineering'],
    'computer_engineering': ['computer engineering'],
    'software_engineering': ['software engineering'],
    'telecommunications': ['telecommunications'],
    'networking': ['networking'],
    'voip': ['VoIP', 'voice over IP'],
    'cloud_computing': ['cloud computing', 'cloud'],
    'cybersecurity': ['cybersecurity', 'security'],
    'data_privacy': ['data privacy'],
    'digital_marketing': ['digital marketing'],
    'content_marketing': ['content marketing'],
    'social_media_marketing': ['social media marketing'],
    'seo': ['SEO', 'search engine optimization'],
    'ppc': ['PPC', 'pay-per-click'],
    'email_marketing': ['email marketing'],
    'analytics': ['analytics'],
    'user_experience': ['user experience', 'UX'],
    'user_interface': ['user interface', 'UI'],
    'conversion_rate_optimization': ['conversion rate optimization', 'CRO'],
    'web_analytics': ['web analytics'],
    'mobile_marketing': ['mobile marketing'],
    'branding': ['branding'],
    'public_relations': ['public relations', 'PR'],
    'event_planning': ['event planning'],
    'customer_relationship_management': ['customer relationship management', 'CRM'],
    'salesforce': ['Salesforce'],
    'hubspot': ['HubSpot'],
    'market_research': ['market research'],
    'competitive_analysis': ['competitive analysis'],
    'financial_analysis': ['financial analysis'],
    'risk_management': ['risk management'],
    'business_strategy': ['business strategy'],
    'strategic_planning': ['strategic planning'],
    'entrepreneurship': ['entrepreneurship'],
    'innovation': ['innovation'],
    'startups': ['startups'],
    'venture_capital': ['venture capital'],
    'angel_investing': ['angel investing'],
    'business_development': ['business development'],
    'mergers_and_acquisitions': ['mergers and acquisitions', 'M&A'],
    'project_management': ['project management'],
    'agile_methodology': ['agile methodology', 'agile'],
    'scrum': ['scrum'],
    'kanban': ['kanban'],
    'lean': ['lean methodology', 'lean'],
    'six_sigma': ['Six Sigma'],
    'change_management': ['change management'],
    'conflict_resolution': ['conflict resolution'],
    'negotiation': ['negotiation'],
    'leadership': ['leadership'],
    'team_management': ['team management'],
    'mentoring': ['mentoring'],
    'coaching': ['coaching'],
    'performance_management': ['performance management'],
    'employee_engagement': ['employee engagement'],
    'talent_management': ['talent management'],
    'organizational_development': ['organizational development'],
    'workplace_culture': ['workplace culture'],
    'employee_wellness': ['employee wellness'],
    'diversity_and_inclusion': ['diversity and inclusion'],
    'employee_relations': ['employee relations'],
    'compensation_and_benefits': ['compensation and benefits'],
    'human_resources_information_system': ['human resources information system', 'HRIS'],
    'recruitment_and_selection': ['recruitment and selection'],
    'onboarding': ['onboarding'],
    'training_and_development': ['training and development'],
    'performance_appraisal': ['performance appraisal'],
    'succession_planning': ['succession planning'],
    'workforce_planning': ['workforce planning'],
    'occupational_health_and_safety': ['occupational health and safety', 'OH&S'],
    'employee_retention': ['employee retention'],
    'labour_law': ['labour law'],
    'employee_rights': ['employee rights'],
    'unemployment_insurance': ['unemployment insurance'],
    'workplace_ethics': ['workplace ethics'],
    'workplace_diversity': ['workplace diversity'],
    'workplace_harassment': ['workplace harassment'],
    'employee_privacy': ['employee privacy'],
    'organizational_communication': ['organizational communication'],
    'strategic_communication': ['strategic communication'],
    'internal_communication': ['internal communication'],
    'external_communication': ['external communication'],
    'crisis_communication': ['crisis communication'],
    'marketing_communication': ['marketing communication'],
    'public_speaking': ['public speaking'],
    'presentation_skills': ['presentation skills'],
    'written_communication': ['written communication'],
    'visual_communication': ['visual communication'],
    'media_relations': ['media relations'],
    'negotiation_skills': ['negotiation skills'],
    'conflict_resolution': ['conflict resolution'],
    'empathy': ['empathy'],
    'active_listening': ['active listening'],
    'feedback': ['feedback'],
    'assertiveness': ['assertiveness'],
    'time_management': ['time management'],
    'prioritization': ['prioritization'],
    'stress_management': ['stress management'],
    'decision_making': ['decision making'],
    'problem_solving': ['problem solving'],
    'creativity': ['creativity'],
    'innovation': ['innovation'],
    'adaptability': ['adaptability'],
    'resilience': ['resilience'],
    'growth_mindset': ['growth mindset'],
    'self_motivation': ['self-motivation'],
    'self_management': ['self-management'],
    'self_awareness': ['self-awareness'],
    'emotional_intelligence': ['emotional intelligence'],
    'leadership': ['leadership'],
    'visionary_leadership': ['visionary leadership'],
    'strategic_leadership': ['strategic leadership'],
    'transformational_leadership': ['transformational leadership'],
    'servant_leadership': ['servant leadership'],
    'team_building': ['team building'],
    'team_collaboration': ['team collaboration'],
    'delegation': ['delegation'],
    'motivation': ['motivation'],
    'coaching': ['coaching'],
    'mentoring': ['mentoring'],
    'communication': ['communication'],
    'conflict_resolution': ['conflict resolution'],
    'negotiation': ['negotiation'],
    'decision_making': ['decision making'],
    'problem_solving': ['problem solving'],
    'time_management': ['time management'],
    'project_management': ['project management'],
    'agile_methodology': ['agile methodology', 'agile'],
    'lean': ['lean methodology', 'lean'],
    'six_sigma': ['Six Sigma'],
    'budgeting': ['budgeting'],
    'financial_analysis': ['financial analysis'],
    'investment_management': ['investment management'],
    'risk_management': ['risk management'],
    'strategic_planning': ['strategic planning'],
    'business_strategy': ['business strategy'],
    'competitive_analysis': ['competitive analysis'],
    'market_research': ['market research'],
    'business_development': ['business development'],
    'entrepreneurship': ['entrepreneurship'],
    'innovation': ['innovation'],
    'change_management': ['change management'],
    'data_analysis': ['data analysis'],
    'data_visualization': ['data visualization'],
    'predictive_modeling': ['predictive modeling'],
    'data_mining': ['data mining'],
    'statistical_analysis': ['statistical analysis'],
    'quantitative_analysis': ['quantitative analysis'],
    'qualitative_analysis': ['qualitative analysis'],
    'machine_learning': ['machine learning'],
    'big_data': ['big data'],
    'data_engineering': ['data engineering'],
    'data_architecture': ['data architecture'],
    'database_management': ['database management'],
    'data_integration': ['data integration'],
    'data_migration': ['data migration'],
    'data_quality': ['data quality'],
    'data_privacy': ['data privacy'],
    'data_governance': ['data governance'],
    'data_stewardship': ['data stewardship'],
    'data_anonymization': ['data anonymization'],
    'data_classification': ['data classification'],
    'data_storage': ['data storage'],
    'data_warehousing': ['data warehousing'],
    'data_catalog': ['data catalog'],
    'data_lineage': ['data lineage'],
    'data_processing': ['data processing'],
    'data_transformations': ['data transformations'],
    'data_preparation': ['data preparation'],
    'data_cleansing': ['data cleansing'],
    'data_wrangling': ['data wrangling'],
    'data_validation': ['data validation'],
    'data_analysis_tools': ['data analysis tools'],
    'data_visualization_tools': ['data visualization tools'],
    'business_intelligence_tools': ['business intelligence tools'],
    'machine_learning_tools': ['machine learning tools'],
    'big_data_tools': ['big data tools'],
    'data_engineering_tools': ['data engineering tools'],
    'data_quality_tools': ['data quality tools'],
    'data_privacy_tools': ['data privacy tools'],
    'data_governance_tools': ['data governance tools'],
    'data_stewardship_tools': ['data stewardship tools'],
    'data_anonymization_tools': ['data anonymization tools'],
    'data_classification_tools': ['data classification tools'],
    'data_storage_tools': ['data storage tools'],
    'data_warehousing_tools': ['data warehousing tools'],
    'data_catalog_tools': ['data catalog tools'],
    'data_lineage_tools': ['data lineage tools'],
    'data_processing_tools': ['data processing tools'],
    'data_transformations_tools': ['data transformations tools'],
    'data_preparation_tools': ['data preparation tools'],
    'data_cleansing_tools': ['data cleansing tools'],
    'data_wrangling_tools': ['data wrangling tools'],
    'data_validation_tools': ['data validation tools'],
    'data_analysis_languages': ['data analysis languages'],
    'data_visualization_languages': ['data visualization languages'],
    'business_intelligence_languages': ['business intelligence languages'],
    'machine_learning_languages': ['machine learning languages'],
    'big_data_languages': ['big data languages'],
    'data_engineering_languages': ['data engineering languages'],
    'data_quality_languages': ['data quality languages'],
    'data_privacy_languages': ['data privacy languages'],
    'data_governance_languages': ['data governance languages'],
    'data_stewardship_languages': ['data stewardship languages'],
    'data_anonymization_languages': ['data anonymization languages'],
    'data_classification_languages': ['data classification languages'],
    'data_storage_languages': ['data storage languages'],
    'data_warehousing_languages': ['data warehousing languages'],
    'data_catalog_languages': ['data catalog languages'],
    'data_lineage_languages': ['data lineage languages'],
    'data_processing_languages': ['data processing languages'],
    'data_transformations_languages': ['data transformations languages'],
    'data_preparation_languages': ['data preparation languages'],
    'data_cleansing_languages': ['data cleansing languages'],
    'data_wrangling_languages': ['data wrangling languages'],
    'data_validation_languages': ['data validation languages'],
    'data_analysis_platforms': ['data analysis platforms'],
    'data_visualization_platforms': ['data visualization platforms'],
    'business_intelligence_platforms': ['business intelligence platforms'],
    'machine_learning_platforms': ['machine learning platforms'],
    'big_data_platforms': ['big data platforms'],
    'data_engineering_platforms': ['data engineering platforms'],
    'data_quality_platforms': ['data quality platforms'],
    'data_privacy_platforms': ['data privacy platforms'],
    'data_governance_platforms': ['data governance platforms'],
    'data_stewardship_platforms': ['data stewardship platforms'],
    'data_anonymization_platforms': ['data anonymization platforms'],
    'data_classification_platforms': ['data classification platforms'],
    'data_storage_platforms': ['data storage platforms'],
    'data_warehousing_platforms': ['data warehousing platforms'],
    'data_catalog_platforms': ['data catalog platforms'],
    'data_lineage_platforms': ['data lineage platforms'],
    'data_processing_platforms': ['data processing platforms'],
    'data_transformations_platforms': ['data transformations platforms'],
    'data_preparation_platforms': ['data preparation platforms'],
    'data_cleansing_platforms': ['data cleansing platforms'],
    'data_wrangling_platforms': ['data wrangling platforms'],
    'data_validation_platforms': ['data validation platforms'],
    'data_engineering_frameworks': ['data engineering frameworks'],
    'data_quality_frameworks': ['data quality frameworks'],
    'data_privacy_frameworks': ['data privacy frameworks'],
    'data_governance_frameworks': ['data governance frameworks'],
    'data_stewardship_frameworks': ['data stewardship frameworks'],
    'data_anonymization_frameworks': ['data anonymization frameworks'],
    'data_classification_frameworks': ['data classification frameworks'],
    'data_storage_frameworks': ['data storage frameworks'],
    'data_warehousing_frameworks': ['data warehousing frameworks'],
    'data_catalog_frameworks': ['data catalog frameworks'],
    'data_lineage_frameworks': ['data lineage frameworks'],
    'data_processing_frameworks': ['data processing frameworks'],
    'data_transformations_frameworks': ['data transformations frameworks'],
    'data_preparation_frameworks': ['data preparation frameworks'],
    'data_cleansing_frameworks': ['data cleansing frameworks'],
    'data_wrangling_frameworks': ['data wrangling frameworks'],
    'data_validation_frameworks': ['data validation frameworks'],
    'data_management': ['data management'],
    'data_strategy': ['data strategy'],
    'data_architecture': ['data architecture'],
    'data_operations': ['data operations'],
    'data_modeling': ['data modeling'],
    'data_warehouse': ['data warehouse'],
    'data_lakes': ['data lakes'],
    'data_marts': ['data marts'],
    'data_integration': ['data integration'],
    'data_migration': ['data migration'],
    'data_quality': ['data quality'],
    'data_privacy': ['data privacy'],
    'data_governance': ['data governance'],
    'data_stewardship': ['data stewardship'],
    'data_anonymization': ['data anonymization'],
    'data_classification': ['data classification'],
    'data_storage': ['data storage'],
    'data_warehousing': ['data warehousing'],
    'data_catalog': ['data catalog'],
    'data_lineage': ['data lineage'],
    'data_processing': ['data processing'],
    'data_transformations': ['data transformations'],
    'data_preparation': ['data preparation'],
    'data_cleansing': ['data cleansing'],
    'data_wrangling': ['data wrangling'],
    'data_validation': ['data validation'],
    'data_analysis_tools': ['data analysis tools'],
    'data_visualization_tools': ['data visualization tools'],
    'business_intelligence_tools': ['business intelligence tools'],
    'machine_learning_tools': ['machine learning tools'],
    'big_data_tools': ['big data tools'],
    'data_engineering_tools': ['data engineering tools'],
    'data_quality_tools': ['data quality tools'],
    'data_privacy_tools': ['data privacy tools'],
    'data_governance_tools': ['data governance tools'],
    'data_stewardship_tools': ['data stewardship tools'],
    'data_anonymization_tools': ['data anonymization tools'],
    'data_classification_tools': ['data classification tools'],
    'data_storage_tools': ['data storage tools'],
    'data_warehousing_tools': ['data warehousing tools'],
    'data_catalog_tools': ['data catalog tools'],
    'data_lineage_tools': ['data lineage tools'],
    'data_processing_tools': ['data processing tools'],
    'data_transformations_tools': ['data transformations tools'],
    'data_preparation_tools': ['data preparation tools'],
    'data_cleansing_tools': ['data cleansing tools'],
    'data_wrangling_tools': ['data wrangling tools'],
    'data_validation_tools': ['data validation tools'],
    'data_analysis_languages': ['data analysis languages'],
    'data_visualization_languages': ['data visualization languages'],
    'business_intelligence_languages': ['business intelligence languages'],
    'machine_learning_languages': ['machine learning languages'],
    'big_data_languages': ['big data languages'],
    'data_engineering_languages': ['data engineering languages'],
    'data_quality_languages': ['data quality languages'],
    'data_privacy_languages': ['data privacy languages'],
    'data_governance_languages': ['data governance languages'],
    'data_stewardship_languages': ['data stewardship languages'],
    'data_anonymization_languages': ['data anonymization languages'],
    'data_classification_languages': ['data classification languages'],
    'data_storage_languages': ['data storage languages'],
    'data_warehousing_languages': ['data warehousing languages'],
    'data_catalog_languages': ['data catalog languages'],
    'data_lineage_languages': ['data lineage languages'],
    'data_processing_languages': ['data processing languages'],
    'data_transformations_languages': ['data transformations languages'],
    'data_preparation_languages': ['data preparation languages'],
    'data_cleansing_languages': ['data cleansing languages'],
    'data_wrangling_languages': ['data wrangling languages'],
    'data_validation_languages': ['data validation languages'],
    'data_analysis_platforms': ['data analysis platforms'],
    'data_visualization_platforms': ['data visualization platforms'],
    'business_intelligence_platforms': ['business intelligence platforms'],
    'machine_learning_platforms': ['machine learning platforms'],
    'big_data_platforms': ['big data platforms'],
    'data_engineering_platforms': ['data engineering platforms'],
    'data_quality_platforms': ['data quality platforms'],
    'data_privacy_platforms': ['data privacy platforms'],
    'data_governance_platforms': ['data governance platforms'],
    'data_stewardship_platforms': ['data stewardship platforms'],
    'data_anonymization_platforms': ['data anonymization platforms'],
    'data_classification_platforms': ['data classification platforms'],
    'data_storage_platforms': ['data storage platforms'],
    'data_warehousing_platforms': ['data warehousing platforms'],
    'data_catalog_platforms': ['data catalog platforms'],
    'data_lineage_platforms': ['data lineage platforms'],
    'data_processing_platforms': ['data processing platforms'],
    'data_transformations_platforms': ['data transformations platforms'],
    'data_preparation_platforms': ['data preparation platforms'],
    'data_cleansing_platforms': ['data cleansing platforms'],
    'data_wrangling_platforms': ['data wrangling platforms'],
    'data_validation_platforms': ['data validation platforms'],
    'data_engineering_frameworks': ['data engineering frameworks'],
    'data_quality_frameworks': ['data quality frameworks'],
    'data_privacy_frameworks': ['data privacy frameworks'],
    'data_governance_frameworks': ['data governance frameworks'],
    'data_stewardship_frameworks': ['data stewardship frameworks'],
    'data_anonymization_frameworks': ['data anonymization frameworks'],
    'data_classification_frameworks': ['data classification frameworks'],
    'data_storage_frameworks': ['data storage frameworks'],
    'data_warehousing_frameworks': ['data warehousing frameworks'],
    'data_catalog_frameworks': ['data catalog frameworks'],
    'data_lineage_frameworks': ['data lineage frameworks'],
    'data_processing_frameworks': ['data processing frameworks'],
    'data_transformations_frameworks': ['data transformations frameworks'],
    'data_preparation_frameworks': ['data preparation frameworks'],
    'data_cleansing_frameworks': ['data cleansing frameworks'],
    'data_wrangling_frameworks': ['data wrangling frameworks'],
    'data_validation_frameworks': ['data validation frameworks'],
    'data_management': ['data management'],
    'data_strategy': ['data strategy'],
    'data_architecture': ['data architecture'],
    'data_operations': ['data operations'],
    'data_modeling': ['data modeling'],
    'data_warehouse': ['data warehouse'],
    'data_lakes': ['data lakes'],
    'data_marts': ['data marts'],
    'data_integration': ['data integration'],
    'data_migration': ['data migration'],
    'data_quality': ['data quality'],
    'data_privacy': ['data privacy'],
    'data_governance': ['data governance'],
    'data_stewardship': ['data stewardship'],
    'data_anonymization': ['data anonymization'],
    'data_classification': ['data classification'],
    'data_storage': ['data storage'],
    'data_warehousing': ['data warehousing'],
    'data_catalog': ['data catalog'],
    'data_lineage': ['data lineage'],
    'data_processing': ['data processing'],
    'data_transformations': ['data transformations'],
    'data_preparation': ['data preparation'],
    'data_cleansing': ['data cleansing'],
    'data_wrangling': ['data wrangling'],
    'data_validation': ['data validation'],
    'data_analysis_tools': ['data analysis tools'],
    'data_visualization_tools': ['data visualization tools'],
    'business_intelligence_tools': ['business intelligence tools'],
    'machine_learning_tools': ['machine learning tools'],
    'big_data_tools': ['big data tools'],
    'data_engineering_tools': ['data engineering tools'],
    'data_quality_tools': ['data quality tools'],
    'data_privacy_tools': ['data privacy tools'],
    'data_governance_tools': ['data governance tools'],
    'data_stewardship_tools': ['data stewardship tools'],
    'data_anonymization_tools': ['data anonymization tools'],
    'data_classification_tools': ['data classification tools'],
    'data_storage_tools': ['data storage tools'],
    'data_warehousing_tools': ['data warehousing tools'],
    'data_catalog_tools': ['data catalog tools'],
    'data_lineage_tools': ['data lineage tools'],
    'data_processing_tools': ['data processing tools'],
    'data_transformations_tools': ['data transformations tools'],
    'data_preparation_tools': ['data preparation tools'],
    'data_cleansing_tools': ['data cleansing tools'],
    'data_wrangling_tools': ['data wrangling tools'],
    'data_validation_tools': ['data validation tools'],
    'data_analysis_languages': ['data analysis languages'],
    'data_visualization_languages': ['data visualization languages'],
    'business_intelligence_languages': ['business intelligence languages'],
    'machine_learning_languages': ['machine learning languages'],
    'big_data_languages': ['big data languages'],
    'data_engineering_languages': ['data engineering languages'],
    'data_quality_languages': ['data quality languages'],
    'data_privacy_languages': ['data privacy languages'],
    'data_governance_languages': ['data governance languages'],
    'data_stewardship_languages': ['data stewardship languages'],
    'data_anonymization_languages': ['data anonymization languages'],
    'data_classification_languages': ['data classification languages'],
    'data_storage_languages': ['data storage languages'],
    'data_warehousing_languages': ['data warehousing languages'],
    'data_catalog_languages': ['data catalog languages'],
    'data_lineage_languages': ['data lineage languages'],
    'data_processing_languages': ['data processing languages'],
    'data_transformations_languages': ['data transformations languages'],
    'data_preparation_languages': ['data preparation languages'],
    'data_cleansing_languages': ['data cleansing languages'],
    'data_wrangling_languages': ['data wrangling languages'],
    'data_validation_languages': ['data validation languages'],
    'data_analysis_platforms': ['data analysis platforms'],
    'data_visualization_platforms': ['data visualization platforms'],
    'business_intelligence_platforms': ['business intelligence platforms'],
    'machine_learning_platforms': ['machine learning platforms'],
    'big_data_platforms': ['big data platforms'],
    'data_engineering_platforms': ['data engineering platforms'],
    'data_quality_platforms': ['data quality platforms'],
    'data_privacy_platforms': ['data privacy platforms'],
    'data_governance_platforms': ['data governance platforms'],
    'data_stewardship_platforms': ['data stewardship platforms'],
    'data_anonymization_platforms': ['data anonymization platforms'],
    'data_classification_platforms': ['data classification platforms'],
    'data_storage_platforms': ['data storage platforms'],
    'data_warehousing_platforms': ['data warehousing platforms'],
    'data_catalog_platforms': ['data catalog platforms'],
    'data_lineage_platforms': ['data lineage platforms'],
    'data_processing_platforms': ['data processing platforms'],
    'data_transformations_platforms': ['data transformations platforms'],
    'data_preparation_platforms': ['data preparation platforms'],
    'data_cleansing_platforms': ['data cleansing platforms'],
    'data_wrangling_platforms': ['data wrangling platforms'],
    'data_validation_platforms': ['data validation platforms'],
    'data_engineering_frameworks': ['data engineering frameworks'],
    'data_quality_frameworks': ['data quality frameworks'],
    'data_privacy_frameworks': ['data privacy frameworks'],
    'data_governance_frameworks': ['data governance frameworks'],
    'data_stewardship_frameworks': ['data stewardship frameworks'],
    'data_anonymization_frameworks': ['data anonymization frameworks'],
    'data_classification_frameworks': ['data classification frameworks'],
    'data_storage_frameworks': ['data storage frameworks'],
    'data_warehousing_frameworks': ['data warehousing frameworks'],
    'data_catalog_frameworks': ['data catalog frameworks'],
    'data_lineage_frameworks': ['data lineage frameworks'],
    'data_processing_frameworks': ['data processing frameworks'],
    'data_transformations_frameworks': ['data transformations frameworks'],
    'data_preparation_frameworks': ['data preparation frameworks'],
    'data_cleansing_frameworks': ['data cleansing frameworks'],
    'data_wrangling_frameworks': ['data wrangling frameworks'],
    'data_validation_frameworks': ['data validation frameworks'],
    'data_management': ['data management'],
    'data_strategy': ['data strategy'],
    'data_architecture': ['data architecture'],
    'data_operations': ['data operations'],
    'data_modeling': ['data modeling'],
    'data_warehouse': ['data warehouse'],
    'data_lakes': ['data lakes'],
    'data_marts': ['data marts'],
    'data_integration': ['data integration'],
    'data_migration': ['data migration'],
    'data_quality': ['data quality'],
    'data_privacy': ['data privacy'],
    'data_governance': ['data governance'],
    'data_stewardship': ['data stewardship'],
    'data_anonymization': ['data anonymization'],
    'data_classification': ['data classification'],
    'data_storage': ['data storage'],
    'data_warehousing': ['data warehousing'],
    'data_catalog': ['data catalog'],
    'data_lineage': ['data lineage'],
    'data_processing': ['data processing'],
    'data_transformations': ['data transformations'],
    'data_preparation': ['data preparation'],
    'data_cleansing': ['data cleansing'],
    'data_wrangling': ['data wrangling'],
    'data_validation': ['data validation'],
    'data_analysis_tools': ['data analysis tools'],
    'data_visualization_tools': ['data visualization tools'],
    'business_intelligence_tools': ['business intelligence tools'],
    'machine_learning_tools': ['machine learning tools'],
    'big_data_tools': ['big data tools'],
    'data_engineering_tools': ['data engineering tools'],
    'data_quality_tools': ['data quality tools'],
    'data_privacy_tools': ['data privacy tools'],
    'data_governance_tools': ['data governance tools'],
    'data_stewardship_tools': ['data stewardship tools'],
    'data_anonymization_tools': ['data anonymization tools'],
    'data_classification_tools': ['data classification tools'],
    'data_storage_tools': ['data storage tools'],
    'data_warehousing_tools': ['data warehousing tools'],
    'data_catalog_tools': ['data catalog tools'],
    'data_lineage_tools': ['data lineage tools'],
    'data_processing_tools': ['data processing tools'],
    'data_transformations_tools': ['data transformations tools'],
    'data_preparation_tools': ['data preparation tools'],
    'data_cleansing_tools': ['data cleansing tools'],
    'data_wrangling_tools': ['data wrangling tools'],
    'data_validation_tools': ['data validation tools'],
    'data_analysis_languages': ['data analysis languages'],
    'data_visualization_languages': ['data visualization languages'],
    'business_intelligence_languages': ['business intelligence languages'],
    'machine_learning_languages': ['machine learning languages'],
    'big_data_languages': ['big data languages'],
    'data_engineering_languages': ['data engineering languages'],
    'data_quality_languages': ['data quality languages'],
    'data_privacy_languages': ['data privacy languages'],
    'data_governance_languages': ['data governance languages'],
    'data_stewardship_languages': ['data stewardship languages'],
    'data_anonymization_languages': ['data anonymization languages'],
    'data_classification_languages': ['data classification languages'],
    'data_storage_languages': ['data storage languages'],
    'data_warehousing_languages': ['data warehousing languages'],
    'data_catalog_languages': ['data catalog languages'],
    'data_lineage_languages': ['data lineage languages'],
    'data_processing_languages': ['data processing languages'],
    'data_transformations_languages': ['data transformations languages'],
    'data_preparation_languages': ['data preparation languages'],
    'data_cleansing_languages': ['data cleansing languages'],
    'data_wrangling_languages': ['data wrangling languages'],
    'data_validation_languages': ['data validation languages'],
}